[build]
builder = "NIXPACKS"
buildCommand = "cd packages/backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd packages/backend && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
